# Airtable
airtable.api.key=patcGSMW6ZC8h2PqO.f95ec37ce544ab5e54dd1862d8d099c92ce5008f04db0214310d14b2f3bb9563
airtable.base.id=appvAg0KJLCLgsLW0
airtable.table.user=tbljvvKlwRmBMXc0z

spring.application.name=LeavingSystem
 server.port=8088

