<<<<<<< HEAD
airtable.api.key=patdw7VIz2QkuYnJU.693c1ddb55b783a0aa8cdbeb0ab9c13536d4b06f3f4c6e38f042af3dd85e114a
airtable.base.id=appvAg0KJLCLgsLW0
airtable.table.user=tbljvvKlwRmBMXc0z
airtable.table.leave=tblKcIfxebHkDuH1d
airtable.table.leavetype=tbl8hccDFEgRiTtrr
airtable.table.leavetype=tbl8hccDFEgRiTtrr
airtable.table.Permission=tblGIJDcyUdPmQIXz


# Spring Boot server port
 server.port=8047
=======
 

spring.application.name=LeavingSystem
 server.port=8088
>>>>>>> c8dc33f085b4f205b3e99d5e031b445c7234d9b3

